CREATE TABLE [gold].[Payment]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[CustomerId] UNIQUEIDENTIFIER NOT NULL,
	[PaymentDate] DATETIME2 NOT NULL,
	[FromDate] DATETIME2 NOT NULL,
	[ToDate] DATETIME2 NOT NULL,
	[Amount] DECIMAL NOT NULL,
	[CreatedOn] DATETIME2 NULL DEFAULT SYSUTCDATETIME(),
    [CreatedBy] UNIQUEIDENTIFIER NULL,
    [UpdatedOn] DATETIME2 NULL,
    [UpdatedBy] UNIQUEIDENTIFIER NULL
	CONSTRAINT FK_CustomerPayment FOREIGN KEY (CustomerId)
    REFERENCES [gold].[Customer] ([Id])
)
